/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace RideHailing {
  export type RideStruct = {
    rider: PromiseOrValue<string>;
    driver: PromiseOrValue<string>;
    fare: PromiseOrValue<BigNumberish>;
    rideCompleted: PromiseOrValue<boolean>;
    estdTime: PromiseOrValue<string>;
    rating: PromiseOrValue<BigNumberish>;
  };

  export type RideStructOutput = [
    string,
    string,
    BigNumber,
    boolean,
    string,
    BigNumber
  ] & {
    rider: string;
    driver: string;
    fare: BigNumber;
    rideCompleted: boolean;
    estdTime: string;
    rating: BigNumber;
  };
}

export interface RideHailingInterface extends utils.Interface {
  functions: {
    "acceptRide(uint256)": FunctionFragment;
    "cancelRide(uint256)": FunctionFragment;
    "completeRideAndRateDriver(uint256,uint256)": FunctionFragment;
    "distance()": FunctionFragment;
    "fulfillDistance(bytes32,string)": FunctionFragment;
    "getPricePerMeter()": FunctionFragment;
    "getRide(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pricePerMeter()": FunctionFragment;
    "registerUser()": FunctionFragment;
    "registeredUsers(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestRide(string,string)": FunctionFragment;
    "rideCount()": FunctionFragment;
    "rides(uint256)": FunctionFragment;
    "setPricePerMeter(uint256)": FunctionFragment;
    "status()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptRide"
      | "cancelRide"
      | "completeRideAndRateDriver"
      | "distance"
      | "fulfillDistance"
      | "getPricePerMeter"
      | "getRide"
      | "owner"
      | "pricePerMeter"
      | "registerUser"
      | "registeredUsers"
      | "renounceOwnership"
      | "requestRide"
      | "rideCount"
      | "rides"
      | "setPricePerMeter"
      | "status"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptRide",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRide",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "completeRideAndRateDriver",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "distance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillDistance",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPricePerMeter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRide",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricePerMeter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRide",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "rideCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rides",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPricePerMeter",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "acceptRide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelRide", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeRideAndRateDriver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "distance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillDistance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPricePerMeter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerMeter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rideCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rides", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPricePerMeter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ChainlinkCancelled(bytes32)": EventFragment;
    "ChainlinkFulfilled(bytes32)": EventFragment;
    "ChainlinkRequested(bytes32)": EventFragment;
    "DriverRated(address,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RequestVolume(bytes32,string)": EventFragment;
    "RideAccepted(address,uint256)": EventFragment;
    "RideCancelled(address,uint256)": EventFragment;
    "RideCompleted(address,uint256)": EventFragment;
    "RideRequested(address,uint256,uint256)": EventFragment;
    "UserRegistered(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChainlinkCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChainlinkFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChainlinkRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DriverRated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestVolume"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RideAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RideCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RideCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RideRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserRegistered"): EventFragment;
}

export interface ChainlinkCancelledEventObject {
  id: string;
}
export type ChainlinkCancelledEvent = TypedEvent<
  [string],
  ChainlinkCancelledEventObject
>;

export type ChainlinkCancelledEventFilter =
  TypedEventFilter<ChainlinkCancelledEvent>;

export interface ChainlinkFulfilledEventObject {
  id: string;
}
export type ChainlinkFulfilledEvent = TypedEvent<
  [string],
  ChainlinkFulfilledEventObject
>;

export type ChainlinkFulfilledEventFilter =
  TypedEventFilter<ChainlinkFulfilledEvent>;

export interface ChainlinkRequestedEventObject {
  id: string;
}
export type ChainlinkRequestedEvent = TypedEvent<
  [string],
  ChainlinkRequestedEventObject
>;

export type ChainlinkRequestedEventFilter =
  TypedEventFilter<ChainlinkRequestedEvent>;

export interface DriverRatedEventObject {
  rider: string;
  rideId: BigNumber;
  rating: BigNumber;
}
export type DriverRatedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  DriverRatedEventObject
>;

export type DriverRatedEventFilter = TypedEventFilter<DriverRatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RequestVolumeEventObject {
  _requestId: string;
  _status: string;
}
export type RequestVolumeEvent = TypedEvent<
  [string, string],
  RequestVolumeEventObject
>;

export type RequestVolumeEventFilter = TypedEventFilter<RequestVolumeEvent>;

export interface RideAcceptedEventObject {
  driver: string;
  rideId: BigNumber;
}
export type RideAcceptedEvent = TypedEvent<
  [string, BigNumber],
  RideAcceptedEventObject
>;

export type RideAcceptedEventFilter = TypedEventFilter<RideAcceptedEvent>;

export interface RideCancelledEventObject {
  rider: string;
  rideId: BigNumber;
}
export type RideCancelledEvent = TypedEvent<
  [string, BigNumber],
  RideCancelledEventObject
>;

export type RideCancelledEventFilter = TypedEventFilter<RideCancelledEvent>;

export interface RideCompletedEventObject {
  rider: string;
  rideId: BigNumber;
}
export type RideCompletedEvent = TypedEvent<
  [string, BigNumber],
  RideCompletedEventObject
>;

export type RideCompletedEventFilter = TypedEventFilter<RideCompletedEvent>;

export interface RideRequestedEventObject {
  rider: string;
  rideId: BigNumber;
  fare: BigNumber;
}
export type RideRequestedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  RideRequestedEventObject
>;

export type RideRequestedEventFilter = TypedEventFilter<RideRequestedEvent>;

export interface UserRegisteredEventObject {
  user: string;
}
export type UserRegisteredEvent = TypedEvent<
  [string],
  UserRegisteredEventObject
>;

export type UserRegisteredEventFilter = TypedEventFilter<UserRegisteredEvent>;

export interface RideHailing extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RideHailingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    completeRideAndRateDriver(
      _rideId: PromiseOrValue<BigNumberish>,
      _rating: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    distance(overrides?: CallOverrides): Promise<[BigNumber]>;

    fulfillDistance(
      _requestId: PromiseOrValue<BytesLike>,
      _status: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPricePerMeter(overrides?: CallOverrides): Promise<[BigNumber]>;

    getRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [RideHailing.RideStructOutput] & { ride: RideHailing.RideStructOutput }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pricePerMeter(overrides?: CallOverrides): Promise<[BigNumber]>;

    registerUser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registeredUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestRide(
      _pickup: PromiseOrValue<string>,
      _drop: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    rideCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    rides(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string, BigNumber] & {
        rider: string;
        driver: string;
        fare: BigNumber;
        rideCompleted: boolean;
        estdTime: string;
        rating: BigNumber;
      }
    >;

    setPricePerMeter(
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    status(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptRide(
    _rideId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelRide(
    _rideId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  completeRideAndRateDriver(
    _rideId: PromiseOrValue<BigNumberish>,
    _rating: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  distance(overrides?: CallOverrides): Promise<BigNumber>;

  fulfillDistance(
    _requestId: PromiseOrValue<BytesLike>,
    _status: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

  getRide(
    _rideId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<RideHailing.RideStructOutput>;

  owner(overrides?: CallOverrides): Promise<string>;

  pricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

  registerUser(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registeredUsers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestRide(
    _pickup: PromiseOrValue<string>,
    _drop: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  rideCount(overrides?: CallOverrides): Promise<BigNumber>;

  rides(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean, string, BigNumber] & {
      rider: string;
      driver: string;
      fare: BigNumber;
      rideCompleted: boolean;
      estdTime: string;
      rating: BigNumber;
    }
  >;

  setPricePerMeter(
    newPrice: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  status(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    completeRideAndRateDriver(
      _rideId: PromiseOrValue<BigNumberish>,
      _rating: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    distance(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillDistance(
      _requestId: PromiseOrValue<BytesLike>,
      _status: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getPricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

    getRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<RideHailing.RideStructOutput>;

    owner(overrides?: CallOverrides): Promise<string>;

    pricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

    registerUser(overrides?: CallOverrides): Promise<void>;

    registeredUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestRide(
      _pickup: PromiseOrValue<string>,
      _drop: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    rideCount(overrides?: CallOverrides): Promise<BigNumber>;

    rides(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string, BigNumber] & {
        rider: string;
        driver: string;
        fare: BigNumber;
        rideCompleted: boolean;
        estdTime: string;
        rating: BigNumber;
      }
    >;

    setPricePerMeter(
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    status(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ChainlinkCancelled(bytes32)"(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkCancelledEventFilter;
    ChainlinkCancelled(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkCancelledEventFilter;

    "ChainlinkFulfilled(bytes32)"(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkFulfilledEventFilter;
    ChainlinkFulfilled(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkFulfilledEventFilter;

    "ChainlinkRequested(bytes32)"(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkRequestedEventFilter;
    ChainlinkRequested(
      id?: PromiseOrValue<BytesLike> | null
    ): ChainlinkRequestedEventFilter;

    "DriverRated(address,uint256,uint256)"(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null,
      rating?: null
    ): DriverRatedEventFilter;
    DriverRated(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null,
      rating?: null
    ): DriverRatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RequestVolume(bytes32,string)"(
      _requestId?: null,
      _status?: null
    ): RequestVolumeEventFilter;
    RequestVolume(_requestId?: null, _status?: null): RequestVolumeEventFilter;

    "RideAccepted(address,uint256)"(
      driver?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideAcceptedEventFilter;
    RideAccepted(
      driver?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideAcceptedEventFilter;

    "RideCancelled(address,uint256)"(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideCancelledEventFilter;
    RideCancelled(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideCancelledEventFilter;

    "RideCompleted(address,uint256)"(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideCompletedEventFilter;
    RideCompleted(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null
    ): RideCompletedEventFilter;

    "RideRequested(address,uint256,uint256)"(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null,
      fare?: null
    ): RideRequestedEventFilter;
    RideRequested(
      rider?: PromiseOrValue<string> | null,
      rideId?: PromiseOrValue<BigNumberish> | null,
      fare?: null
    ): RideRequestedEventFilter;

    "UserRegistered(address)"(
      user?: PromiseOrValue<string> | null
    ): UserRegisteredEventFilter;
    UserRegistered(
      user?: PromiseOrValue<string> | null
    ): UserRegisteredEventFilter;
  };

  estimateGas: {
    acceptRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    completeRideAndRateDriver(
      _rideId: PromiseOrValue<BigNumberish>,
      _rating: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    distance(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillDistance(
      _requestId: PromiseOrValue<BytesLike>,
      _status: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

    getRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pricePerMeter(overrides?: CallOverrides): Promise<BigNumber>;

    registerUser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registeredUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestRide(
      _pickup: PromiseOrValue<string>,
      _drop: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    rideCount(overrides?: CallOverrides): Promise<BigNumber>;

    rides(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPricePerMeter(
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    status(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    completeRideAndRateDriver(
      _rideId: PromiseOrValue<BigNumberish>,
      _rating: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    distance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fulfillDistance(
      _requestId: PromiseOrValue<BytesLike>,
      _status: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPricePerMeter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRide(
      _rideId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pricePerMeter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerUser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registeredUsers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestRide(
      _pickup: PromiseOrValue<string>,
      _drop: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    rideCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rides(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPricePerMeter(
      newPrice: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    status(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
